package com.vetx.starter.model;

public enum SpecialityName {
  GENERAL_GUIDANCE,
  SAFETY_OBSERVER,
  SERVICE_DEPUTY,
  GENERAL_SERVICE_WORKER,
  DRIVER,
  CRANE_DRIVER,
  LEVADOROS_KOUMANTADOROS,
  EFARMOSTIS_MONTADOROS,
  ELASMATOURGOS
}
